<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="3" total="4" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-15T23:07:30 IST" name="Default suite" finished-at="2022-08-15T23:08:39 IST" duration-ms="68528">
    <groups>
      <group name="regression">
        <method signature="LoginPageTest.VerifyTitle()[pri:0, instance:TestCases.LoginPageTest@793be5ca]" name="VerifyTitle" class="TestCases.LoginPageTest"/>
      </group> <!-- regression -->
    </groups>
    <test started-at="2022-08-15T23:07:30 IST" name="Default test" finished-at="2022-08-15T23:08:39 IST" duration-ms="68528">
      <class name="TestCases.LoginPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:TestCases.LoginPageTest@793be5ca]" started-at="2022-08-15T23:07:30 IST" name="setup" finished-at="2022-08-15T23:08:38 IST" duration-ms="67165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="VerifyTitle()[pri:0, instance:TestCases.LoginPageTest@793be5ca]" started-at="2022-08-15T23:08:38 IST" name="VerifyTitle" finished-at="2022-08-15T23:08:38 IST" duration-ms="60" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1Kite - Zerodha's fast and elegant flagship trading platform] but found [Kite - Zerodha's fast and elegant flagship trading platform]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1Kite - Zerodha's fast and elegant flagship trading platform] but found [Kite - Zerodha's fast and elegant flagship trading platform]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at TestCases.LoginPageTest.VerifyTitle(LoginPageTest.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyTitle -->
        <test-method is-config="true" signature="exit(org.testng.ITestResult)[pri:0, instance:TestCases.LoginPageTest@793be5ca]" started-at="2022-08-15T23:08:38 IST" name="exit" finished-at="2022-08-15T23:08:39 IST" duration-ms="1253" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyTitle status=FAILURE method=LoginPageTest.VerifyTitle()[pri:0, instance:TestCases.LoginPageTest@793be5ca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- exit -->
      </class> <!-- TestCases.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
